# Generated by Django 5.2.4 on 2025-07-25 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='bug',
            name='ai_suggestion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
